import { computeChecksum } from "@/lib/crypto";

/**
 * Script Renderer
 *
 * Renders deployment scripts from templates with variable substitution.
 * All generated scripts are transparent — no hidden behavior.
 */

export interface RenderOptions {
  profileName: string;
  profileSlug: string;
  variables?: Record<string, string>;
  extraPackages?: string[];
  envVars?: Record<string, string>;
  postInstallCmds?: string[];
  autoReboot?: boolean;
}

/**
 * Render a shell script from a template with variable substitution.
 */
export function renderShellScript(template: string, options: RenderOptions): string {
  let script = template;

  // Replace template variables {{VAR_NAME}}
  if (options.variables) {
    for (const [key, value] of Object.entries(options.variables)) {
      script = script.replace(new RegExp(`\\{\\{${key}\\}\\}`, "g"), value);
    }
  }

  // Add extra packages
  if (options.extraPackages && options.extraPackages.length > 0) {
    script += `\n\n# ── Extra Packages ──\napt-get install -y ${options.extraPackages.join(" ")} || yum install -y ${options.extraPackages.join(" ")}\n`;
  }

  // Add env vars
  if (options.envVars && Object.keys(options.envVars).length > 0) {
    script += `\n# ── Environment Variables ──\n`;
    for (const [key, value] of Object.entries(options.envVars)) {
      script += `export ${key}="${value}"\n`;
    }
  }

  // Add post-install commands
  if (options.postInstallCmds && options.postInstallCmds.length > 0) {
    script += `\n# ── Post-Install Commands ──\n`;
    for (const cmd of options.postInstallCmds) {
      script += `${cmd}\n`;
    }
  }

  // Add auto-reboot
  if (options.autoReboot) {
    script += `\n# ── Auto Reboot ──\necho "System will reboot in 10 seconds..."\nsleep 10\nreboot\n`;
  }

  return script;
}

/**
 * Render a cloud-init YAML template with variable substitution.
 */
export function renderCloudInit(template: string, options: RenderOptions): string {
  let yaml = template;

  if (options.variables) {
    for (const [key, value] of Object.entries(options.variables)) {
      yaml = yaml.replace(new RegExp(`\\{\\{${key}\\}\\}`, "g"), value);
    }
  }

  return yaml;
}

/**
 * Generate a bootstrap command for a given script URL and checksum.
 */
export function generateBootstrapCommand(
  scriptContent: string,
  baseUrl: string,
  profileSlug: string
): {
  curlBash: string;
  safeVariant: string;
  checksum: string;
} {
  const checksum = computeChecksum(scriptContent);

  const curlBash = `curl -fsSL ${baseUrl}/api/bootstrap/script/${profileSlug} | bash`;

  const safeVariant = `# Safer: Download, inspect, then run
curl -fsSL ${baseUrl}/api/bootstrap/script/${profileSlug} -o myinstaller_${profileSlug}.sh
echo "Expected checksum: ${checksum}"
sha256sum myinstaller_${profileSlug}.sh
# Review the script:
cat myinstaller_${profileSlug}.sh
# Run if everything looks correct:
chmod +x myinstaller_${profileSlug}.sh
./myinstaller_${profileSlug}.sh`;

  return { curlBash, safeVariant, checksum };
}

/**
 * Generate a hardening script.
 */
export function generateHardeningScript(): string {
  return `#!/bin/bash
# ══════════════════════════════════════════════════════════════════════════════
# MyInstaller — System Hardening Script
# Generated by MyInstaller. Review before running.
# This script applies basic security hardening. Adjust to your needs.
# ══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

echo "=== MyInstaller Hardening Script ==="
echo "Date: $(date -u)"
echo ""

# Update system packages
echo "→ Updating system packages..."
apt-get update -qq && apt-get upgrade -y -qq || yum update -y -q

# Configure automatic security updates
echo "→ Configuring automatic security updates..."
apt-get install -y -qq unattended-upgrades 2>/dev/null || true

# SSH hardening
echo "→ Hardening SSH configuration..."
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup
sed -i 's/#PermitRootLogin yes/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config
sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
sed -i 's/X11Forwarding yes/X11Forwarding no/' /etc/ssh/sshd_config

# Install and configure fail2ban
echo "→ Installing fail2ban..."
apt-get install -y -qq fail2ban 2>/dev/null || yum install -y -q fail2ban 2>/dev/null || true
systemctl enable fail2ban 2>/dev/null || true
systemctl start fail2ban 2>/dev/null || true

# Configure firewall basics
echo "→ Configuring basic firewall rules..."
if command -v ufw &>/dev/null; then
  ufw default deny incoming
  ufw default allow outgoing
  ufw allow ssh
  ufw --force enable
fi

# Kernel hardening
echo "→ Applying kernel hardening..."
cat >> /etc/sysctl.d/99-myinstaller-hardening.conf <<'SYSCTL'
# Prevent IP spoofing
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
# Disable source routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
# Ignore ICMP broadcast requests
net.ipv4.icmp_echo_ignore_broadcasts = 1
# Log martian packets
net.ipv4.conf.all.log_martians = 1
SYSCTL
sysctl -p /etc/sysctl.d/99-myinstaller-hardening.conf 2>/dev/null || true

echo ""
echo "=== Hardening complete ==="
echo "Note: Review SSH config changes and test connectivity before disconnecting."
echo "Restart SSH: systemctl restart sshd"
`;
}

/**
 * Generate a dry-run validation script.
 */
export function generateDryRunScript(profileName: string): string {
  return `#!/bin/bash
# ══════════════════════════════════════════════════════════════════════════════
# MyInstaller — Dry Run Validation Script
# Profile: ${profileName}
# This script validates the target system WITHOUT making changes.
# ══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

echo "=== MyInstaller Dry Run Validation ==="
echo "Profile: ${profileName}"
echo "Date: $(date -u)"
echo ""

echo "→ Checking OS..."
cat /etc/os-release 2>/dev/null || echo "Cannot determine OS"

echo ""
echo "→ Checking disk space..."
df -h / 2>/dev/null

echo ""
echo "→ Checking memory..."
free -h 2>/dev/null || echo "free command not available"

echo ""
echo "→ Checking network..."
ip addr show 2>/dev/null | head -20 || ifconfig 2>/dev/null | head -20

echo ""
echo "→ Checking package manager..."
if command -v apt-get &>/dev/null; then
  echo "Package manager: apt (Debian/Ubuntu)"
elif command -v yum &>/dev/null; then
  echo "Package manager: yum (RHEL/CentOS)"
elif command -v apk &>/dev/null; then
  echo "Package manager: apk (Alpine)"
else
  echo "Unknown package manager"
fi

echo ""
echo "→ Checking available ports..."
ss -tlnp 2>/dev/null | head -10 || netstat -tlnp 2>/dev/null | head -10

echo ""
echo "=== Dry run validation complete ==="
echo "No changes were made to the system."
`;
}
